rails:
  build: .
  restart: always
  env_file: ../../.env.production
  volumes:
    - /home/app/rails/rnplay:/app
    - /home/app/repos:/var/repos
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: production
    PASSENGER_RAILS_ENV: production
    VIRTUAL_HOST: rnplay.org,www.rnplay.org

postgres:
  restart: always
  env_file: ../../.env.production
  image: postgres

redis:
  restart: always
  image: redis

cache:
  restart: always
  image: memcached

worker:
  restart: always
  build: .
  command: bundle exec sidekiq -e production -c 25
  volumes:
    - /home/app/rails/rnplay:/app
  env_file: ../../.env.production
  links:
    - postgres
    - redis
    - cache

packager0330:
  restart: always
  image: packager:0.33.0
  environment:
    VIRTUAL_HOST: packager0330.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/app/js
    - /home/app/rails/rnplay/public/.well-known:/app/.well-known
